const express = require('express');
const customersRouter = require('./customers');
const subscriptionsRouter = require('./subscriptions');
const eventsRouter = require('./events');
const invoicesRouter = require('./invoices');
const creditsRouter = require('./credits');
const couponsRouter = require('./coupons');
const appliedCouponsRouter = require('./applied_coupons');
const addOnsRouter = require('./add_ons');
const plansRouter = require('./plans');
const billableMetricsRouter = require('./billable_metrics');
const walletsRouter = require('./wallets');
const taxesRouter = require('./taxes');
const webhookEndpointsRouter = require('./webhook_endpoints');
const customerUsageRouter = require('./customer_usage');
const organizationsRouter = require('./organizations');
const feesRouter = require('./fees');
const paymentsRouter = require('./payments');
const paymentMethodsRouter = require('./payment_methods');
const paymentReceiptsRouter = require('./payment_receipts');
const paymentRequestsRouter = require('./payment_requests');
const billingEntitiesRouter = require('./billing_entities');
const alertsRouter = require('./alerts');
const auditLogsRouter = require('./audit_logs');
const entitlementsRouter = require('./entitlements');
const resourcesRouter = require('./resources');
const webhooksRouter = require('./webhooks');

const router = express.Router();

// Mount all route modules
router.use('/customers', customersRouter);
router.use('/subscriptions', subscriptionsRouter);
router.use('/events', eventsRouter);
router.use('/invoices', invoicesRouter);
router.use('/credits', creditsRouter);
router.use('/coupons', couponsRouter);
router.use('/applied_coupons', appliedCouponsRouter);
router.use('/add_ons', addOnsRouter);
router.use('/plans', plansRouter);
router.use('/billable_metrics', billableMetricsRouter);
router.use('/wallets', walletsRouter);
router.use('/taxes', taxesRouter);
router.use('/webhook_endpoints', webhookEndpointsRouter);
router.use('/customer_usage', customerUsageRouter);
router.use('/organizations', organizationsRouter);
router.use('/fees', feesRouter);
router.use('/payments', paymentsRouter);
router.use('/payment_methods', paymentMethodsRouter);
router.use('/payment_receipts', paymentReceiptsRouter);
router.use('/payment_requests', paymentRequestsRouter);
router.use('/billing_entities', billingEntitiesRouter);
router.use('/alerts', alertsRouter);
router.use('/audit_logs', auditLogsRouter);
router.use('/entitlements', entitlementsRouter);
router.use('/resources', resourcesRouter);
router.use('/webhooks', webhooksRouter);

module.exports = router;
